
server:
  port: 9885


spring:
  profiles:
    active: dev
  application:
    name: BeeExpress-OMS-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null


management:
  security:
    enabled: true
  context-path: /bee

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000



auth:
  serviceId: BeeExpress-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: BeeExpress-OMS-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    pub-key:
      path: client/pub.key

id-generator:
  machine-code: 1  # id生成器机器掩码


pagehelper:
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


