server:
  port: 9890
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    status-page-url: http://172.21.247.49:9770/api/tms/swagger-ui.html
#    hostname: ${eureka.hostname:eureka.BeeExpress.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
  rabbitmq:
      host: 172.21.247.52
      port: 5672
      password: admin
      username: admin
  redis:
    host: 172.21.247.52
    port: 6379
    password: Bee@9394
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: prod1
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://BeeExpress-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
#    rabbitmq:
#      queue: zipkin
bee:
  mysql:
    admin:
      database: beeexpress_tms       # 根据环境更改
      driverClassName: ${bee.mysql.driverClassName}
      host: ${bee.mysql.host}
      password: ${bee.mysql.password}
      port: ${bee.mysql.port}
      url: jdbc:mysql://${bee.mysql.admin.host}:${bee.mysql.admin.port}/${bee.mysql.admin.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: ${bee.mysql.username}
    #driverClassName: com.mysql.cj.jdbc.Driver  # 6.0.6
    driverClassName: com.mysql.jdbc.Driver    # 5.x
    host: rm-t4nez14383p79rq04to.mysql.singapore.rds.aliyuncs.com             # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: Bee^6&7*8
swagger2:
  package: com.BeeExpress.tms.controller
  service:
    name: tms 后台管理
    description: tms后台管理服务
    contact:
      name: 最后
      url: http://www.BeeExpress.com/
      email: tangstruggle@sina.com