management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /bee
security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证




server:
  port: 8515

turbine:
  stream:
    port: 8516

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
#  mail:
#    host: smtp.163.com
#    username: aaa@163.com
#    password: aaa
#    properties:
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#          required: true
