

spring:
  profiles:
    active: dev
  application:
    name: BeeExpress-zipkin
  sleuth:
    enabled: false # 表示当前程序不使用sleuth


# 表示zipkin数据存储方式是mysql
zipkin:
  storage:
    type: mysql
#  collector:
#    http:
#      enabled: true  # 这里开启了http模式，不确定是走rabbitmq，还是http 进行监控的
#    rabbitmq:
#      addresses: BeeExpress.rabbitmq.host:5672
#      username: guest
#      password: guest
#      queue: zipkin

server:
  port: 8510

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    preferIpAddress: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /bee

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证


