

spring:
  profiles:
    active: test
  application:
    name: BeeExpress-zipkin





server:
  port: 8510

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    preferIpAddress: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /bee

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证


