

spring:
  application:
    name: BeeExpress-auth-server
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 # 并发执行的最大线程数，默认10
      maxQueueSize: 1000 # BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000




management:
  security:
    enabled: true
  context-path: /bee


client:
  id: BeeExpress-auth-server
  secret: 123456
  token-header: token
  admin-header: _isAdmin
  expire: 7200
  pri-key: # client 私钥
    path: client/pri.key
  pub-key:
    path: client/pub.key

id-generator:
  machine-code: 1  # id生成器机器掩码

