info:
  artifact: BeeExpress-file-server
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'

# 日志
logging:
  path: ./logs/BeeExpress-file-server
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

# 端口号
server:
  port: 9755

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    status-page-url: http://${BeeExpress.hostname.gateway:gateway.BeeExpress.com}:9770/api/file/swagger-ui.html
#    hostname: ${eureka.hostname:eureka.BeeExpress.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

# bean 转换
dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

# spring配置
spring:
  application:
    name: BeeExpress-file-server
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
  redis:
    host: 192.168.1.118
    port: 6379
    password: Bee@9394
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
  rabbitmq:
    host: 192.168.1.118
    port: 5672
    password: admin
    username: admin
  sleuth:
    sampler:
      percentage: 0.5
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://BeeExpress-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
#    rabbitmq:
#      queue: zipkin

# actuator端点 以及 actuator端点的权限
management:
  security:
    enabled: true
  context-path: /bee
security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

feign:
  hystrix:
    enabled: true

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# 文档配置
swagger2:
  package: com.BeeExpress.file.rest
  service:
    name: 文件服务
    description: 文件服务
    contact:
      name: 最后
      url: http://www.BeeExpress.com/
      email: tangstruggle@sina.com

# 认证客服端配置
auth:
  serviceId: BeeExpress-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: BeeExpress-file-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    pub-key:
      path: client/pub.key

 # id生成器机器掩码
id-generator:
  machine-code: 1

# 文件上传相关信息
bee:
  mysql:
    admin:
      database: BeeExpress_admin_dev       # 根据环境更改
      driverClassName: ${bee.mysql.driverClassName}
      host: ${bee.mysql.host}
      password: ${bee.mysql.password}
      port: ${bee.mysql.port}
      url: jdbc:mysql://${bee.mysql.admin.host}:${bee.mysql.admin.port}/${bee.mysql.admin.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: ${BeeExpress.mysql.username}
    #driverClassName: com.mysql.cj.jdbc.Driver  # 6.0.6
    driverClassName: com.mysql.jdbc.Driver    # 5.x
    host: BeeExpress.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: KCbNT3bC2QWYqXKaa9gM55lCDmEWYEkJW1U6VvwBe44xkyeXH6MoPzGQjL/1YkyoGIsbM/TEO+i8ZlZLbO9iMw==
  file:
    upload-path-prefix: /home/BeeExpress/uploadfile/
    remote-uri-prefix: http://192.168.65.147:6080/
    fastdfs:
      enabled: true
  hostname:
    gateway: 127.0.0.1
