server:
  port: 9765
  
logging:
  common-pattern: '%d{HH:mm:ss.SSS}:[%5p] [%t] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

spring:
  #rabbitmq:
   # host: BeeExpress.rabbitmq.host
    #port: 5672
    #password: guest
    #username: guest
  redis:
    host: 192.168.1.118 
    port: 6379
    key-prefix: dev
BeeExpress:
  mysql:
    admin:
      database: BeeExpress_admin_dev       # 根据环境更改
    host: BeeExpress.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: lzl123
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。

id-generator:
  machine-code: 1  # id生成器机器掩码

test: dev_修改2
hello: dev_hello_修改2
