server:
  port: 9895
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    status-page-url: http://gateway.BeeExpress.com:9770/api/openapi/swagger-ui.html
#    hostname: ${eureka.hostname:eureka.BeeExpress.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
  rabbitmq:
      host: 192.168.1.118
      port: 5672
      password: admin
      username: admin
      publisher-confirms: true
      publisher-returns: true
      listener:
          simple:
              acknowledge-mode: manual #采用手动应答
              concurrency: 1 #指定最小的消费数量
              max-concurrency: 1 #指定最大的消费者数量
              retry:
                 enabled: true

  redis:
    host: 192.168.1.118
    port: 6379
    password: Bee@9394
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: dev
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://BeeExpress-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
#    rabbitmq:
#      queue: zipkin
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M

bee:
  mysql:
    admin:
      database: BeeExpress_openapi       # 根据环境更改
      driverClassName: ${bee.mysql.driverClassName}
      host: ${bee.mysql.host}
      password: ${bee.mysql.password}
      port: ${bee.mysql.port}
      url: jdbc:mysql://${bee.mysql.admin.host}:${bee.mysql.admin.port}/${bee.mysql.admin.database}?serverTimezone=CTT&allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
      username: ${bee.mysql.username}
    #driverClassName: com.mysql.cj.jdbc.Driver  # 6.0.6
    driverClassName: com.mysql.jdbc.Driver    # 5.x
    host: 192.168.1.128     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: Bee123456
swagger2:
  package: com.BeeExpress.openapi.controller
  service:
    name:  BeeExpress开放平台
    description: BeeExpress开放平台
    contact:
      name: BeeExpress
      url: http://www.BeeExpress.com/
      email: tangstruggle@sina.com