shiro:
  realm: com.BeeExpress.center.shiro.ShiroAuthorizingRealm
  loginUrl: http://center.BeeExpress.com:${server.port}/login
  successUrl: http://center.BeeExpress.com:${server.port}/index
  unauthorizedUrl: http://center.BeeExpress.com:${server.port}/unauthorized
  filterChainDefinitions:
    anon:
      - /login
      - /register
      - /static/**
      - /mgmt/**
      - /webjars/**
    logout:
      - /logout
    authc:
      /**

BeeExpress:
  variable:
    gate-way-url-prefix: http://127.0.0.1:9970

server:
  port: 9740

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
